void SRB2_maxDR_SR_SRB_Higgsino_N_1()
{
//=========Macro generated from canvas: Canvas1/Canvas1
//=========  (Mon Jun  4 23:13:20 2018) by ROOT version 6.12/06
   TCanvas *Canvas1 = new TCanvas("Canvas1", "Canvas1",0,22,900,756);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Canvas1->SetHighLightColor(2);
   Canvas1->Range(0,0,1,1);
   Canvas1->SetFillColor(0);
   Canvas1->SetBorderMode(0);
   Canvas1->SetBorderSize(2);
   Canvas1->SetLogy();
   Canvas1->SetTickx(1);
   Canvas1->SetTicky(1);
   Canvas1->SetLeftMargin(0.16);
   Canvas1->SetRightMargin(0.05);
   Canvas1->SetTopMargin(0.05);
   Canvas1->SetBottomMargin(0.16);
   Canvas1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0.3,1,1);
   pad1->Draw();
   pad1->cd();
   pad1->Range(-1.21509,-2.30103,6.379847,3.572426);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetLogy();
   pad1->SetTickx(1);
   pad1->SetTicky(1);
   pad1->SetLeftMargin(0.16);
   pad1->SetRightMargin(0.05);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0);
   pad1->SetFrameBorderMode(0);
   pad1->SetFrameBorderMode(0);
   
   TH1D *SMBkgPlot__1 = new TH1D("SMBkgPlot__1","Title",12,0.0001,6.0001);
   SMBkgPlot__1->SetBinContent(1,0.0649593);
   SMBkgPlot__1->SetBinContent(2,2.071911);
   SMBkgPlot__1->SetBinContent(3,3.493475);
   SMBkgPlot__1->SetBinContent(4,2.938142);
   SMBkgPlot__1->SetBinContent(5,0.6143357);
   SMBkgPlot__1->SetBinContent(6,0.1947923);
   SMBkgPlot__1->SetBinContent(7,0.3125168);
   SMBkgPlot__1->SetBinError(1,0.03763167);
   SMBkgPlot__1->SetBinError(2,0.9533906);
   SMBkgPlot__1->SetBinError(3,1.258155);
   SMBkgPlot__1->SetBinError(4,1.097449);
   SMBkgPlot__1->SetBinError(5,0.5538567);
   SMBkgPlot__1->SetBinError(6,0.08890945);
   SMBkgPlot__1->SetBinError(7,0.2587501);
   SMBkgPlot__1->SetMinimum(0.005);
   SMBkgPlot__1->SetMaximum(1900);
   SMBkgPlot__1->SetEntries(170);
   SMBkgPlot__1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#999999");
   SMBkgPlot__1->SetFillColor(ci);
   SMBkgPlot__1->SetFillStyle(3004);
   SMBkgPlot__1->SetLineWidth(7);

   ci = TColor::GetColor("#ff0000");
   SMBkgPlot__1->SetMarkerColor(ci);
   SMBkgPlot__1->SetMarkerStyle(20);
   SMBkgPlot__1->SetMarkerSize(0.001);
   SMBkgPlot__1->GetXaxis()->SetTitle("SRB2_maxDR");
   SMBkgPlot__1->GetXaxis()->SetRange(1,12);
   SMBkgPlot__1->GetXaxis()->SetLabelFont(42);
   SMBkgPlot__1->GetXaxis()->SetLabelSize(0.05);
   SMBkgPlot__1->GetXaxis()->SetTitleSize(0.05);
   SMBkgPlot__1->GetXaxis()->SetTitleOffset(1.4);
   SMBkgPlot__1->GetXaxis()->SetTitleFont(42);
   SMBkgPlot__1->GetYaxis()->SetTitle("Events / #frac{#Pi}{10}");
   SMBkgPlot__1->GetYaxis()->SetLabelFont(42);
   SMBkgPlot__1->GetYaxis()->SetLabelSize(0.045);
   SMBkgPlot__1->GetYaxis()->SetTitleSize(0.045);
   SMBkgPlot__1->GetYaxis()->SetTitleOffset(1.5);
   SMBkgPlot__1->GetYaxis()->SetTitleFont(42);
   SMBkgPlot__1->GetZaxis()->SetLabelFont(42);
   SMBkgPlot__1->GetZaxis()->SetLabelSize(0.05);
   SMBkgPlot__1->GetZaxis()->SetTitleSize(0.05);
   SMBkgPlot__1->GetZaxis()->SetTitleFont(42);
   SMBkgPlot__1->Draw("HIST;E2");
   
   TH1D *SMBkgPlot__2 = new TH1D("SMBkgPlot__2","Title",12,0.0001,6.0001);
   SMBkgPlot__2->SetBinContent(1,0.0649593);
   SMBkgPlot__2->SetBinContent(2,2.071911);
   SMBkgPlot__2->SetBinContent(3,3.493475);
   SMBkgPlot__2->SetBinContent(4,2.938142);
   SMBkgPlot__2->SetBinContent(5,0.6143357);
   SMBkgPlot__2->SetBinContent(6,0.1947923);
   SMBkgPlot__2->SetBinContent(7,0.3125168);
   SMBkgPlot__2->SetBinError(1,0.03763167);
   SMBkgPlot__2->SetBinError(2,0.9533906);
   SMBkgPlot__2->SetBinError(3,1.258155);
   SMBkgPlot__2->SetBinError(4,1.097449);
   SMBkgPlot__2->SetBinError(5,0.5538567);
   SMBkgPlot__2->SetBinError(6,0.08890945);
   SMBkgPlot__2->SetBinError(7,0.2587501);
   SMBkgPlot__2->SetEntries(170);
   SMBkgPlot__2->SetStats(0);
   SMBkgPlot__2->SetLineWidth(7);

   ci = TColor::GetColor("#ff0000");
   SMBkgPlot__2->SetMarkerColor(ci);
   SMBkgPlot__2->SetMarkerStyle(20);
   SMBkgPlot__2->SetMarkerSize(1e-09);
   SMBkgPlot__2->GetXaxis()->SetRange(1,12);
   SMBkgPlot__2->GetXaxis()->SetLabelFont(42);
   SMBkgPlot__2->GetXaxis()->SetLabelSize(0.05);
   SMBkgPlot__2->GetXaxis()->SetTitleSize(0.05);
   SMBkgPlot__2->GetXaxis()->SetTitleOffset(1.4);
   SMBkgPlot__2->GetXaxis()->SetTitleFont(42);
   SMBkgPlot__2->GetYaxis()->SetLabelFont(42);
   SMBkgPlot__2->GetYaxis()->SetLabelSize(0.05);
   SMBkgPlot__2->GetYaxis()->SetTitleSize(0.05);
   SMBkgPlot__2->GetYaxis()->SetTitleOffset(1.4);
   SMBkgPlot__2->GetYaxis()->SetTitleFont(42);
   SMBkgPlot__2->GetZaxis()->SetLabelFont(42);
   SMBkgPlot__2->GetZaxis()->SetLabelSize(0.05);
   SMBkgPlot__2->GetZaxis()->SetTitleSize(0.05);
   SMBkgPlot__2->GetZaxis()->SetTitleFont(42);
   SMBkgPlot__2->Draw("same;HIST");
   
   THStack *hs = new THStack();
   hs->SetName("hs");
   hs->SetTitle("");
   
   TH1F *hs_stack_1 = new TH1F("hs_stack_1","",12,0.0001,6.0001);
   hs_stack_1->SetMinimum(0.00162992);
   hs_stack_1->SetMaximum(6.51968);
   hs_stack_1->SetDirectory(0);
   hs_stack_1->SetStats(0);
   hs_stack_1->SetLineWidth(2);
   hs_stack_1->SetMarkerStyle(20);
   hs_stack_1->SetMarkerSize(1.2);
   hs_stack_1->GetXaxis()->SetLabelFont(42);
   hs_stack_1->GetXaxis()->SetLabelSize(0.05);
   hs_stack_1->GetXaxis()->SetTitleSize(0.05);
   hs_stack_1->GetXaxis()->SetTitleOffset(1.4);
   hs_stack_1->GetXaxis()->SetTitleFont(42);
   hs_stack_1->GetYaxis()->SetLabelFont(42);
   hs_stack_1->GetYaxis()->SetLabelSize(0.05);
   hs_stack_1->GetYaxis()->SetTitleSize(0.05);
   hs_stack_1->GetYaxis()->SetTitleOffset(1.4);
   hs_stack_1->GetYaxis()->SetTitleFont(42);
   hs_stack_1->GetZaxis()->SetLabelFont(42);
   hs_stack_1->GetZaxis()->SetLabelSize(0.05);
   hs_stack_1->GetZaxis()->SetTitleSize(0.05);
   hs_stack_1->GetZaxis()->SetTitleFont(42);
   hs->SetHistogram(hs_stack_1);
   
   
   TH1D *DiBosonPlot_stack_1 = new TH1D("DiBosonPlot_stack_1","Title",12,0.0001,6.0001);
   DiBosonPlot_stack_1->SetStats(0);

   ci = TColor::GetColor("#cc0000");
   DiBosonPlot_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#cc0000");
   DiBosonPlot_stack_1->SetLineColor(ci);
   DiBosonPlot_stack_1->SetMarkerStyle(20);
   DiBosonPlot_stack_1->SetMarkerSize(1.2);
   DiBosonPlot_stack_1->GetXaxis()->SetRange(1,12);
   DiBosonPlot_stack_1->GetXaxis()->SetLabelFont(42);
   DiBosonPlot_stack_1->GetXaxis()->SetLabelSize(0.05);
   DiBosonPlot_stack_1->GetXaxis()->SetTitleSize(0.05);
   DiBosonPlot_stack_1->GetXaxis()->SetTitleOffset(1.4);
   DiBosonPlot_stack_1->GetXaxis()->SetTitleFont(42);
   DiBosonPlot_stack_1->GetYaxis()->SetLabelFont(42);
   DiBosonPlot_stack_1->GetYaxis()->SetLabelSize(0.05);
   DiBosonPlot_stack_1->GetYaxis()->SetTitleSize(0.05);
   DiBosonPlot_stack_1->GetYaxis()->SetTitleOffset(1.4);
   DiBosonPlot_stack_1->GetYaxis()->SetTitleFont(42);
   DiBosonPlot_stack_1->GetZaxis()->SetLabelFont(42);
   DiBosonPlot_stack_1->GetZaxis()->SetLabelSize(0.05);
   DiBosonPlot_stack_1->GetZaxis()->SetTitleSize(0.05);
   DiBosonPlot_stack_1->GetZaxis()->SetTitleFont(42);
   hs->Add(DiBosonPlot_stack_1,"");
   
   TH1D *ZjetsPlot_stack_2 = new TH1D("ZjetsPlot_stack_2","Title",12,0.0001,6.0001);
   ZjetsPlot_stack_2->SetBinContent(2,0.06147044);
   ZjetsPlot_stack_2->SetBinContent(3,0.3457872);
   ZjetsPlot_stack_2->SetBinContent(4,0.2749378);
   ZjetsPlot_stack_2->SetBinContent(5,0.04542606);
   ZjetsPlot_stack_2->SetBinContent(6,0.011971);
   ZjetsPlot_stack_2->SetBinError(2,0.03310669);
   ZjetsPlot_stack_2->SetBinError(3,0.1782174);
   ZjetsPlot_stack_2->SetBinError(4,0.1377032);
   ZjetsPlot_stack_2->SetBinError(5,0.03219253);
   ZjetsPlot_stack_2->SetBinError(6,0.011971);
   ZjetsPlot_stack_2->SetEntries(23);
   ZjetsPlot_stack_2->SetStats(0);

   ci = TColor::GetColor("#0099ff");
   ZjetsPlot_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#0099ff");
   ZjetsPlot_stack_2->SetLineColor(ci);
   ZjetsPlot_stack_2->SetMarkerStyle(20);
   ZjetsPlot_stack_2->SetMarkerSize(1.2);
   ZjetsPlot_stack_2->GetXaxis()->SetRange(1,12);
   ZjetsPlot_stack_2->GetXaxis()->SetLabelFont(42);
   ZjetsPlot_stack_2->GetXaxis()->SetLabelSize(0.05);
   ZjetsPlot_stack_2->GetXaxis()->SetTitleSize(0.05);
   ZjetsPlot_stack_2->GetXaxis()->SetTitleOffset(1.4);
   ZjetsPlot_stack_2->GetXaxis()->SetTitleFont(42);
   ZjetsPlot_stack_2->GetYaxis()->SetLabelFont(42);
   ZjetsPlot_stack_2->GetYaxis()->SetLabelSize(0.05);
   ZjetsPlot_stack_2->GetYaxis()->SetTitleSize(0.05);
   ZjetsPlot_stack_2->GetYaxis()->SetTitleOffset(1.4);
   ZjetsPlot_stack_2->GetYaxis()->SetTitleFont(42);
   ZjetsPlot_stack_2->GetZaxis()->SetLabelFont(42);
   ZjetsPlot_stack_2->GetZaxis()->SetLabelSize(0.05);
   ZjetsPlot_stack_2->GetZaxis()->SetTitleSize(0.05);
   ZjetsPlot_stack_2->GetZaxis()->SetTitleFont(42);
   hs->Add(ZjetsPlot_stack_2,"");
   
   TH1D *ttVPlot_stack_3 = new TH1D("ttVPlot_stack_3","Title",12,0.0001,6.0001);
   ttVPlot_stack_3->SetBinContent(2,0.3797718);
   ttVPlot_stack_3->SetBinContent(3,0.2226875);
   ttVPlot_stack_3->SetBinContent(4,0.0275462);
   ttVPlot_stack_3->SetBinContent(5,-0.1865512);
   ttVPlot_stack_3->SetBinContent(6,0.04755219);
   ttVPlot_stack_3->SetBinContent(7,0.02045336);
   ttVPlot_stack_3->SetBinError(2,0.1809934);
   ttVPlot_stack_3->SetBinError(3,0.2170797);
   ttVPlot_stack_3->SetBinError(4,0.1040187);
   ttVPlot_stack_3->SetBinError(5,0.1064371);
   ttVPlot_stack_3->SetBinError(6,0.04839271);
   ttVPlot_stack_3->SetBinError(7,0.02045336);
   ttVPlot_stack_3->SetEntries(60);
   ttVPlot_stack_3->SetStats(0);

   ci = TColor::GetColor("#009900");
   ttVPlot_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#009900");
   ttVPlot_stack_3->SetLineColor(ci);
   ttVPlot_stack_3->SetMarkerStyle(20);
   ttVPlot_stack_3->SetMarkerSize(1.2);
   ttVPlot_stack_3->GetXaxis()->SetRange(1,12);
   ttVPlot_stack_3->GetXaxis()->SetLabelFont(42);
   ttVPlot_stack_3->GetXaxis()->SetLabelSize(0.05);
   ttVPlot_stack_3->GetXaxis()->SetTitleSize(0.05);
   ttVPlot_stack_3->GetXaxis()->SetTitleOffset(1.4);
   ttVPlot_stack_3->GetXaxis()->SetTitleFont(42);
   ttVPlot_stack_3->GetYaxis()->SetLabelFont(42);
   ttVPlot_stack_3->GetYaxis()->SetLabelSize(0.05);
   ttVPlot_stack_3->GetYaxis()->SetTitleSize(0.05);
   ttVPlot_stack_3->GetYaxis()->SetTitleOffset(1.4);
   ttVPlot_stack_3->GetYaxis()->SetTitleFont(42);
   ttVPlot_stack_3->GetZaxis()->SetLabelFont(42);
   ttVPlot_stack_3->GetZaxis()->SetLabelSize(0.05);
   ttVPlot_stack_3->GetZaxis()->SetTitleSize(0.05);
   ttVPlot_stack_3->GetZaxis()->SetTitleFont(42);
   hs->Add(ttVPlot_stack_3,"");
   
   TH1D *WjetsPlot_stack_4 = new TH1D("WjetsPlot_stack_4","Title",12,0.0001,6.0001);
   WjetsPlot_stack_4->SetBinContent(3,0.0137886);
   WjetsPlot_stack_4->SetBinContent(4,0.436929);
   WjetsPlot_stack_4->SetBinContent(7,0.2553083);
   WjetsPlot_stack_4->SetBinError(3,0.0137886);
   WjetsPlot_stack_4->SetBinError(4,0.3853534);
   WjetsPlot_stack_4->SetBinError(7,0.2553083);
   WjetsPlot_stack_4->SetEntries(6);
   WjetsPlot_stack_4->SetStats(0);

   ci = TColor::GetColor("#ff9900");
   WjetsPlot_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#ff9900");
   WjetsPlot_stack_4->SetLineColor(ci);
   WjetsPlot_stack_4->SetMarkerStyle(20);
   WjetsPlot_stack_4->SetMarkerSize(1.2);
   WjetsPlot_stack_4->GetXaxis()->SetRange(1,12);
   WjetsPlot_stack_4->GetXaxis()->SetLabelFont(42);
   WjetsPlot_stack_4->GetXaxis()->SetLabelSize(0.05);
   WjetsPlot_stack_4->GetXaxis()->SetTitleSize(0.05);
   WjetsPlot_stack_4->GetXaxis()->SetTitleOffset(1.4);
   WjetsPlot_stack_4->GetXaxis()->SetTitleFont(42);
   WjetsPlot_stack_4->GetYaxis()->SetLabelFont(42);
   WjetsPlot_stack_4->GetYaxis()->SetLabelSize(0.05);
   WjetsPlot_stack_4->GetYaxis()->SetTitleSize(0.05);
   WjetsPlot_stack_4->GetYaxis()->SetTitleOffset(1.4);
   WjetsPlot_stack_4->GetYaxis()->SetTitleFont(42);
   WjetsPlot_stack_4->GetZaxis()->SetLabelFont(42);
   WjetsPlot_stack_4->GetZaxis()->SetLabelSize(0.05);
   WjetsPlot_stack_4->GetZaxis()->SetTitleSize(0.05);
   WjetsPlot_stack_4->GetZaxis()->SetTitleFont(42);
   hs->Add(WjetsPlot_stack_4,"");
   
   TH1D *SingleTopPlot_stack_5 = new TH1D("SingleTopPlot_stack_5","Title",12,0.0001,6.0001);
   SingleTopPlot_stack_5->SetBinContent(3,0.06121012);
   SingleTopPlot_stack_5->SetBinContent(4,0.1305388);
   SingleTopPlot_stack_5->SetBinContent(6,0.05865241);
   SingleTopPlot_stack_5->SetBinError(3,0.06121012);
   SingleTopPlot_stack_5->SetBinError(4,0.09274644);
   SingleTopPlot_stack_5->SetBinError(6,0.05865241);
   SingleTopPlot_stack_5->SetEntries(4);
   SingleTopPlot_stack_5->SetStats(0);

   ci = TColor::GetColor("#99ff99");
   SingleTopPlot_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#99ff99");
   SingleTopPlot_stack_5->SetLineColor(ci);
   SingleTopPlot_stack_5->SetMarkerStyle(20);
   SingleTopPlot_stack_5->SetMarkerSize(1.2);
   SingleTopPlot_stack_5->GetXaxis()->SetRange(1,12);
   SingleTopPlot_stack_5->GetXaxis()->SetLabelFont(42);
   SingleTopPlot_stack_5->GetXaxis()->SetLabelSize(0.05);
   SingleTopPlot_stack_5->GetXaxis()->SetTitleSize(0.05);
   SingleTopPlot_stack_5->GetXaxis()->SetTitleOffset(1.4);
   SingleTopPlot_stack_5->GetXaxis()->SetTitleFont(42);
   SingleTopPlot_stack_5->GetYaxis()->SetLabelFont(42);
   SingleTopPlot_stack_5->GetYaxis()->SetLabelSize(0.05);
   SingleTopPlot_stack_5->GetYaxis()->SetTitleSize(0.05);
   SingleTopPlot_stack_5->GetYaxis()->SetTitleOffset(1.4);
   SingleTopPlot_stack_5->GetYaxis()->SetTitleFont(42);
   SingleTopPlot_stack_5->GetZaxis()->SetLabelFont(42);
   SingleTopPlot_stack_5->GetZaxis()->SetLabelSize(0.05);
   SingleTopPlot_stack_5->GetZaxis()->SetTitleSize(0.05);
   SingleTopPlot_stack_5->GetZaxis()->SetTitleFont(42);
   hs->Add(SingleTopPlot_stack_5,"");
   
   TH1D *HiggsPlot_stack_6 = new TH1D("HiggsPlot_stack_6","Title",12,0.0001,6.0001);
   HiggsPlot_stack_6->SetStats(0);
   HiggsPlot_stack_6->SetFillColor(6);
   HiggsPlot_stack_6->SetLineColor(6);
   HiggsPlot_stack_6->SetMarkerStyle(20);
   HiggsPlot_stack_6->SetMarkerSize(1.2);
   HiggsPlot_stack_6->GetXaxis()->SetRange(1,12);
   HiggsPlot_stack_6->GetXaxis()->SetLabelFont(42);
   HiggsPlot_stack_6->GetXaxis()->SetLabelSize(0.05);
   HiggsPlot_stack_6->GetXaxis()->SetTitleSize(0.05);
   HiggsPlot_stack_6->GetXaxis()->SetTitleOffset(1.4);
   HiggsPlot_stack_6->GetXaxis()->SetTitleFont(42);
   HiggsPlot_stack_6->GetYaxis()->SetLabelFont(42);
   HiggsPlot_stack_6->GetYaxis()->SetLabelSize(0.05);
   HiggsPlot_stack_6->GetYaxis()->SetTitleSize(0.05);
   HiggsPlot_stack_6->GetYaxis()->SetTitleOffset(1.4);
   HiggsPlot_stack_6->GetYaxis()->SetTitleFont(42);
   HiggsPlot_stack_6->GetZaxis()->SetLabelFont(42);
   HiggsPlot_stack_6->GetZaxis()->SetLabelSize(0.05);
   HiggsPlot_stack_6->GetZaxis()->SetTitleSize(0.05);
   HiggsPlot_stack_6->GetZaxis()->SetTitleFont(42);
   hs->Add(HiggsPlot_stack_6,"");
   
   TH1D *ttbarPlot_stack_7 = new TH1D("ttbarPlot_stack_7","Title",12,0.0001,6.0001);
   ttbarPlot_stack_7->SetBinContent(1,0.0649593);
   ttbarPlot_stack_7->SetBinContent(2,1.630669);
   ttbarPlot_stack_7->SetBinContent(3,2.850001);
   ttbarPlot_stack_7->SetBinContent(4,2.06819);
   ttbarPlot_stack_7->SetBinContent(5,0.7554609);
   ttbarPlot_stack_7->SetBinContent(6,0.07661675);
   ttbarPlot_stack_7->SetBinContent(7,0.03675514);
   ttbarPlot_stack_7->SetBinError(1,0.03763167);
   ttbarPlot_stack_7->SetBinError(2,0.9354673);
   ttbarPlot_stack_7->SetBinError(3,1.224799);
   ttbarPlot_stack_7->SetBinError(4,1.008719);
   ttbarPlot_stack_7->SetBinError(5,0.5425791);
   ttbarPlot_stack_7->SetBinError(6,0.044493);
   ttbarPlot_stack_7->SetBinError(7,0.03675514);
   ttbarPlot_stack_7->SetEntries(77);
   ttbarPlot_stack_7->SetStats(0);

   ci = TColor::GetColor("#00ccff");
   ttbarPlot_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff6600");
   ttbarPlot_stack_7->SetLineColor(ci);
   ttbarPlot_stack_7->SetMarkerStyle(20);
   ttbarPlot_stack_7->SetMarkerSize(1.2);
   ttbarPlot_stack_7->GetXaxis()->SetRange(1,12);
   ttbarPlot_stack_7->GetXaxis()->SetLabelFont(42);
   ttbarPlot_stack_7->GetXaxis()->SetLabelSize(0.05);
   ttbarPlot_stack_7->GetXaxis()->SetTitleSize(0.05);
   ttbarPlot_stack_7->GetXaxis()->SetTitleOffset(1.4);
   ttbarPlot_stack_7->GetXaxis()->SetTitleFont(42);
   ttbarPlot_stack_7->GetYaxis()->SetLabelFont(42);
   ttbarPlot_stack_7->GetYaxis()->SetLabelSize(0.05);
   ttbarPlot_stack_7->GetYaxis()->SetTitleSize(0.05);
   ttbarPlot_stack_7->GetYaxis()->SetTitleOffset(1.4);
   ttbarPlot_stack_7->GetYaxis()->SetTitleFont(42);
   ttbarPlot_stack_7->GetZaxis()->SetLabelFont(42);
   ttbarPlot_stack_7->GetZaxis()->SetLabelSize(0.05);
   ttbarPlot_stack_7->GetZaxis()->SetTitleSize(0.05);
   ttbarPlot_stack_7->GetZaxis()->SetTitleFont(42);
   hs->Add(ttbarPlot_stack_7,"");
   hs->Draw("same;hist");
   
   TH1D *signalPlot__3 = new TH1D("signalPlot__3","Title",12,0.0001,6.0001);
   signalPlot__3->SetBinContent(2,0.0001916125);
   signalPlot__3->SetBinContent(3,9.176758);
   signalPlot__3->SetBinContent(4,5.454877);
   signalPlot__3->SetBinContent(5,1.546799);
   signalPlot__3->SetBinContent(6,1.049661);
   signalPlot__3->SetBinError(2,0.0001916125);
   signalPlot__3->SetBinError(3,2.121985);
   signalPlot__3->SetBinError(4,1.587065);
   signalPlot__3->SetBinError(5,0.916528);
   signalPlot__3->SetBinError(6,0.7485379);
   signalPlot__3->SetEntries(37);
   signalPlot__3->SetStats(0);

   ci = TColor::GetColor("#ff00ff");
   signalPlot__3->SetLineColor(ci);
   signalPlot__3->SetLineStyle(2);
   signalPlot__3->SetLineWidth(3);
   signalPlot__3->SetMarkerStyle(20);
   signalPlot__3->SetMarkerSize(1.2);
   signalPlot__3->GetXaxis()->SetRange(1,12);
   signalPlot__3->GetXaxis()->SetLabelFont(42);
   signalPlot__3->GetXaxis()->SetLabelSize(0.05);
   signalPlot__3->GetXaxis()->SetTitleSize(0.05);
   signalPlot__3->GetXaxis()->SetTitleOffset(1.4);
   signalPlot__3->GetXaxis()->SetTitleFont(42);
   signalPlot__3->GetYaxis()->SetLabelFont(42);
   signalPlot__3->GetYaxis()->SetLabelSize(0.05);
   signalPlot__3->GetYaxis()->SetTitleSize(0.05);
   signalPlot__3->GetYaxis()->SetTitleOffset(1.4);
   signalPlot__3->GetYaxis()->SetTitleFont(42);
   signalPlot__3->GetZaxis()->SetLabelFont(42);
   signalPlot__3->GetZaxis()->SetLabelSize(0.05);
   signalPlot__3->GetZaxis()->SetTitleSize(0.05);
   signalPlot__3->GetZaxis()->SetTitleFont(42);
   signalPlot__3->Draw("SAME;HIST");
   TLatex *   tex = new TLatex(0.195,0.87,"#sqrt{s} = 13 TeV, 79.9 fb^{-1}");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.195,0.92,"#it{#bf{ATLAS}} Internal");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.195,0.82,"SR_SRB_Higgsino_N-1");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.59,0.68,0.99,0.94,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("DataPlot","Data","P");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(62);
   entry=leg->AddEntry("SMBkgPlot","SM Total","L");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(7);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ttbarPlot_stack_7","t#bar{t}","F");

   ci = TColor::GetColor("#00ccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff6600");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("WjetsPlot_stack_4","W + Jets","F");

   ci = TColor::GetColor("#ff9900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("SingleTopPlot_stack_5","Single t","F");

   ci = TColor::GetColor("#99ff99");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#99ff99");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ZjetsPlot_stack_2","Z + Jets","F");

   ci = TColor::GetColor("#0099ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0099ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ttVPlot_stack_3","t#bar{t}+V","F");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#009900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("DiBosonPlot_stack_1","DiBoson","F");

   ci = TColor::GetColor("#cc0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cc0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("HiggsPlot_stack_6","Higgs","F");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("signalPlot","(m_{#tilde{b}}, m_{#tilde{#chi}_{2}^{0}}, m_{#tilde{#chi}_{1}^{0}}) = (700, 580, 450)GeV","L");

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   TLine *line1 = new TLine(3,0,3,10);
   line1->SetLineColor(kBlack);
   line1->SetLineWidth(5);
   
   TArrow *arrow = new TArrow(3,10,2.9,10,0.01,">");
   arrow->SetLineWidth(5);
   line1->Draw();
   arrow->Draw();

   leg->Draw();
   pad1->Modified();
   Canvas1->cd();
  
// ------------>Primitives in pad: pad2
   TPad *pad2 = new TPad("pad2", "pad2",0,0.065,1,0.3);
   pad2->Draw();
   pad2->cd();
   pad2->Range(-1.21509,-1.633333,6.379847,2.2);
   pad2->SetFillColor(0);
   pad2->SetBorderMode(0);
   pad2->SetBorderSize(2);
   pad2->SetTickx(1);
   pad2->SetTicky(1);
   pad2->SetLeftMargin(0.16);
   pad2->SetRightMargin(0.05);
   pad2->SetTopMargin(0);
   pad2->SetBottomMargin(0.4);
   pad2->SetFrameBorderMode(0);
   pad2->SetFrameBorderMode(0);
   
   TH1D *SMBkgPlot__4 = new TH1D("SMBkgPlot__4","Title",12,0.0001,6.0001);
   SMBkgPlot__4->SetBinContent(1,1);
   SMBkgPlot__4->SetBinContent(2,1);
   SMBkgPlot__4->SetBinContent(3,1);
   SMBkgPlot__4->SetBinContent(4,1);
   SMBkgPlot__4->SetBinContent(5,1);
   SMBkgPlot__4->SetBinContent(6,1);
   SMBkgPlot__4->SetBinContent(7,1);
   SMBkgPlot__4->SetBinError(1,0.8192701);
   SMBkgPlot__4->SetBinError(2,0.6507509);
   SMBkgPlot__4->SetBinError(3,0.5093209);
   SMBkgPlot__4->SetBinError(4,0.5282345);
   SMBkgPlot__4->SetBinError(5,1.27499);
   SMBkgPlot__4->SetBinError(6,0.6454923);
   SMBkgPlot__4->SetBinError(7,1.170906);
   SMBkgPlot__4->SetMinimum(-0.1);
   SMBkgPlot__4->SetMaximum(2.2);
   SMBkgPlot__4->SetEntries(9.709892);
   SMBkgPlot__4->SetStats(0);
   SMBkgPlot__4->SetFillColor(1);
   SMBkgPlot__4->SetFillStyle(3013);

   ci = TColor::GetColor("#ff0000");
   SMBkgPlot__4->SetMarkerColor(ci);
   SMBkgPlot__4->SetMarkerStyle(20);
   SMBkgPlot__4->SetMarkerSize(1e-05);
   SMBkgPlot__4->GetXaxis()->SetTitle("SRB2_maxDR");
   SMBkgPlot__4->GetXaxis()->SetRange(1,12);
   SMBkgPlot__4->GetXaxis()->SetLabelFont(42);
   SMBkgPlot__4->GetXaxis()->SetLabelSize(0.12);
   SMBkgPlot__4->GetXaxis()->SetTitleSize(0.12);
   SMBkgPlot__4->GetXaxis()->SetTitleFont(42);
   SMBkgPlot__4->GetYaxis()->SetTitle("Data / SM");
   SMBkgPlot__4->GetYaxis()->CenterTitle(true);
   SMBkgPlot__4->GetYaxis()->SetNdivisions(603);
   SMBkgPlot__4->GetYaxis()->SetLabelFont(42);
   SMBkgPlot__4->GetYaxis()->SetLabelSize(0.12);
   SMBkgPlot__4->GetYaxis()->SetTitleSize(0.12);
   SMBkgPlot__4->GetYaxis()->SetTitleOffset(0.5);
   SMBkgPlot__4->GetYaxis()->SetTitleFont(42);
   SMBkgPlot__4->GetZaxis()->SetLabelFont(42);
   SMBkgPlot__4->GetZaxis()->SetLabelSize(0.05);
   SMBkgPlot__4->GetZaxis()->SetTitleSize(0.05);
   SMBkgPlot__4->GetZaxis()->SetTitleFont(42);
   SMBkgPlot__4->Draw("E2");
   TLine *line = new TLine(0.0001,1,6.0001,1);

   ci = TColor::GetColor("#ff0000");
   line->SetLineColor(ci);
   line->Draw();
   pad2->Modified();
   Canvas1->cd();
   Canvas1->Modified();
   Canvas1->cd();
   Canvas1->SetSelected(Canvas1);
}
